version: "3.5"

services:
  db:
    image: "postgres:14"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: "paypalDatabase"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_USER: "postgresTest"